### ISSUE TITLE
optional_id not used

### ISSUE THREAD

**Issue by mbongaerts** [shuzhao-li/mummichog#1]
Dear Shuzhao-li,

In the input file there is a column "optional_id". However, nowhere in the output files this optional id is found. It would be very useful if for a given match also this id is shown in the output. 
Let me know of this is possible. Thanks in advance!

**Comment by shuzhao-li** [comment]
I think this was fixed somewhere along the way. Thanks for the pointer.

**Comment by shuzhao-li** [comment]
Sorry I put a wrong comment on this issue. 
Optional_id is inherited in the file of user input data, but is not used for computation at this moment. In stead, row_number is used as unique ID for tracking user input data.
The idea of having an optional ID is to accommodate partial annotation. We are addressing this issue in version 3, which is under development.
