### ISSUE TITLE
Other models

### ISSUE THREAD

**Issue by bblum9** [shuzhao-li/mummichog#2]
Hello,

Will you continue to add the other models to this version (e.g. BioCyc, mouse, yeast, etc)?

Thanks!

**Comment by shuzhao-li** [comment]
Yes, development now continues as my lab moved to JAX. Coming soon.

**Comment by shuzhao-li** [comment]
See updated README on how to use custom model. 
But version 3 will roll out soon, and this version 2 will be dated.
