### ISSUE TITLE
Column headers in output are incorrect

### ISSUE THREAD

**Issue by trivedi-group** [shuzhao-li/mummichog#3]
I am failing to replicate this on local machine but every time I process my data through mummichog server, I am able to reproduce it.

When the output files are downloaded, the file in tables/userInputData.txt has headers wrongly assigned. The retention time in actual user input data is under column heading 'Statistics' and t-stat data from actual user input data is under column heading 'retention_time'. Not a big deal but may go unnoticed or feel like an error.

**Comment by shuzhao-li** [comment]
I think this was fixed somewhere along the way. Thanks for the pointer.
