### ISSUE TITLE
Considering allowing user adducts?

### ISSUE THREAD

**Issue by joannawolthuis** [shuzhao-li/mummichog#4]
Hi there! Thanks for a really cool tool :) I'd like to integrate it in a tool I'm working on, which heavily features an adduct table that users can edit - I'd love it if I could include those as considered matches in Mummichog (especially if you could allow users to define which m/z values are allowed as potential matches for each metabolite). I saw that currently this is hardcoded in - is there a workaround to make it work this way or would you consider it?
Currently I'm doing the implementation through MetaboAnalystR, but I'd be OK with doing the wrapper myself ^^

Kind regards,
Joanna

**Comment by shuzhao-li** [comment]
Thanks for bringing this up, Joanna. 
On mummichog-server, there's option to specify adducts. We will continue having this available.
Jeff Xia lab maintains MetaboAnalystR, which is a different project.

**Comment by joannawolthuis** [comment]
Hi! Thank you for your answer :) I see the possibility of picking adducts on the server function, does this also work in the command line?

Furthermore, to clarify what I meant, I would be very enthusiastic about the option of adding 'custom' adducts that are not in your server from as far as I could tell, like M+NaCl+H and others - perhaps with a table like this one as part of the command line input: http://maltese.dbs.aber.ac.uk:8888/hrmet/search/disprules.php

Or as an (easier) alternative, would you consider directly having users input matches for each of the KEGG ids so I can do the matching on my side?

**Comment by shuzhao-li** [comment]
To use very "custom" adducts, it'd be easier to run your own copy by modifying config.py for now.

Annotation is a key issue and warrants more discussion. 
Annotation comes from different methods of different confidence levels, and most won't be definitive in the near future of metabolomics. The core of mummichog is to do pathway/network analysis by incorporating the uncertainty of annotation. We are designing a probabilistic data model to accommodate various annotations from different methods (MS/MS, IM-MS, partial annotation, etc). This is a key part of next version. Stay tuned :)
